version: 2
jobs:
  build:
    working_directory: ~/hello-circleci
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: hello-circleci-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install

      # Store bundle cache
      - type: cache-save
        key: hello-circleci-{{ checksum "Gemfile.lock" }}
        paths:
         - ./

      # Run Danger
      - run: bundle exec danger

